// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package presto;

public final class ProfileOuterClass {
  private ProfileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:presto.Profile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */
    int getMtd2FreqCount();
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */
    boolean containsMtd2Freq(
        java.lang.String key);
    /**
     * Use {@link #getMtd2FreqMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Double>
    getMtd2Freq();
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Double>
    getMtd2FreqMap();
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */

    double getMtd2FreqOrDefault(
        java.lang.String key,
        double defaultValue);
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */

    double getMtd2FreqOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code presto.Profile}
   */
  public  static final class Profile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:presto.Profile)
      ProfileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Profile.newBuilder() to construct.
    private Profile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Profile() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Profile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Profile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mtd2Freq_ = com.google.protobuf.MapField.newMapField(
                    Mtd2FreqDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              mtd2Freq__ = input.readMessage(
                  Mtd2FreqDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mtd2Freq_.getMutableMap().put(
                  mtd2Freq__.getKey(), mtd2Freq__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return presto.ProfileOuterClass.internal_static_presto_Profile_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMtd2Freq();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return presto.ProfileOuterClass.internal_static_presto_Profile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              presto.ProfileOuterClass.Profile.class, presto.ProfileOuterClass.Profile.Builder.class);
    }

    public static final int MTD2FREQ_FIELD_NUMBER = 1;
    private static final class Mtd2FreqDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Double>newDefaultInstance(
                  presto.ProfileOuterClass.internal_static_presto_Profile_Mtd2freqEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> mtd2Freq_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
    internalGetMtd2Freq() {
      if (mtd2Freq_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            Mtd2FreqDefaultEntryHolder.defaultEntry);
      }
      return mtd2Freq_;
    }

    public int getMtd2FreqCount() {
      return internalGetMtd2Freq().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */

    public boolean containsMtd2Freq(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMtd2Freq().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMtd2FreqMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getMtd2Freq() {
      return getMtd2FreqMap();
    }
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Double> getMtd2FreqMap() {
      return internalGetMtd2Freq().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */

    public double getMtd2FreqOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMtd2Freq().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
     */

    public double getMtd2FreqOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMtd2Freq().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMtd2Freq(),
          Mtd2FreqDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
           : internalGetMtd2Freq().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
        mtd2Freq__ = Mtd2FreqDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, mtd2Freq__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof presto.ProfileOuterClass.Profile)) {
        return super.equals(obj);
      }
      presto.ProfileOuterClass.Profile other = (presto.ProfileOuterClass.Profile) obj;

      if (!internalGetMtd2Freq().equals(
          other.internalGetMtd2Freq())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetMtd2Freq().getMap().isEmpty()) {
        hash = (37 * hash) + MTD2FREQ_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMtd2Freq().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static presto.ProfileOuterClass.Profile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static presto.ProfileOuterClass.Profile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static presto.ProfileOuterClass.Profile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static presto.ProfileOuterClass.Profile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(presto.ProfileOuterClass.Profile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code presto.Profile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:presto.Profile)
        presto.ProfileOuterClass.ProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return presto.ProfileOuterClass.internal_static_presto_Profile_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMtd2Freq();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableMtd2Freq();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return presto.ProfileOuterClass.internal_static_presto_Profile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                presto.ProfileOuterClass.Profile.class, presto.ProfileOuterClass.Profile.Builder.class);
      }

      // Construct using presto.ProfileOuterClass.Profile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableMtd2Freq().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return presto.ProfileOuterClass.internal_static_presto_Profile_descriptor;
      }

      @java.lang.Override
      public presto.ProfileOuterClass.Profile getDefaultInstanceForType() {
        return presto.ProfileOuterClass.Profile.getDefaultInstance();
      }

      @java.lang.Override
      public presto.ProfileOuterClass.Profile build() {
        presto.ProfileOuterClass.Profile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public presto.ProfileOuterClass.Profile buildPartial() {
        presto.ProfileOuterClass.Profile result = new presto.ProfileOuterClass.Profile(this);
        int from_bitField0_ = bitField0_;
        result.mtd2Freq_ = internalGetMtd2Freq();
        result.mtd2Freq_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof presto.ProfileOuterClass.Profile) {
          return mergeFrom((presto.ProfileOuterClass.Profile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(presto.ProfileOuterClass.Profile other) {
        if (other == presto.ProfileOuterClass.Profile.getDefaultInstance()) return this;
        internalGetMutableMtd2Freq().mergeFrom(
            other.internalGetMtd2Freq());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        presto.ProfileOuterClass.Profile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (presto.ProfileOuterClass.Profile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Double> mtd2Freq_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetMtd2Freq() {
        if (mtd2Freq_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              Mtd2FreqDefaultEntryHolder.defaultEntry);
        }
        return mtd2Freq_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetMutableMtd2Freq() {
        onChanged();;
        if (mtd2Freq_ == null) {
          mtd2Freq_ = com.google.protobuf.MapField.newMapField(
              Mtd2FreqDefaultEntryHolder.defaultEntry);
        }
        if (!mtd2Freq_.isMutable()) {
          mtd2Freq_ = mtd2Freq_.copy();
        }
        return mtd2Freq_;
      }

      public int getMtd2FreqCount() {
        return internalGetMtd2Freq().getMap().size();
      }
      /**
       * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
       */

      public boolean containsMtd2Freq(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMtd2Freq().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMtd2FreqMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double> getMtd2Freq() {
        return getMtd2FreqMap();
      }
      /**
       * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Double> getMtd2FreqMap() {
        return internalGetMtd2Freq().getMap();
      }
      /**
       * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
       */

      public double getMtd2FreqOrDefault(
          java.lang.String key,
          double defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetMtd2Freq().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
       */

      public double getMtd2FreqOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetMtd2Freq().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMtd2Freq() {
        internalGetMutableMtd2Freq().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
       */

      public Builder removeMtd2Freq(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMtd2Freq().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double>
      getMutableMtd2Freq() {
        return internalGetMutableMtd2Freq().getMutableMap();
      }
      /**
       * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
       */
      public Builder putMtd2Freq(
          java.lang.String key,
          double value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableMtd2Freq().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; mtd2freq = 1;</code>
       */

      public Builder putAllMtd2Freq(
          java.util.Map<java.lang.String, java.lang.Double> values) {
        internalGetMutableMtd2Freq().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:presto.Profile)
    }

    // @@protoc_insertion_point(class_scope:presto.Profile)
    private static final presto.ProfileOuterClass.Profile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new presto.ProfileOuterClass.Profile();
    }

    public static presto.ProfileOuterClass.Profile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Profile>
        PARSER = new com.google.protobuf.AbstractParser<Profile>() {
      @java.lang.Override
      public Profile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Profile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Profile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Profile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public presto.ProfileOuterClass.Profile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProfileIntOrBuilder extends
      // @@protoc_insertion_point(interface_extends:presto.ProfileInt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */
    int getMtd2FreqCount();
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */
    boolean containsMtd2Freq(
        java.lang.String key);
    /**
     * Use {@link #getMtd2FreqMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Long>
    getMtd2Freq();
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.Long>
    getMtd2FreqMap();
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */

    long getMtd2FreqOrDefault(
        java.lang.String key,
        long defaultValue);
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */

    long getMtd2FreqOrThrow(
        java.lang.String key);

    /**
     * <code>int64 sum = 3;</code>
     * @return The sum.
     */
    long getSum();
  }
  /**
   * Protobuf type {@code presto.ProfileInt}
   */
  public  static final class ProfileInt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:presto.ProfileInt)
      ProfileIntOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProfileInt.newBuilder() to construct.
    private ProfileInt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProfileInt() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProfileInt();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProfileInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mtd2Freq_ = com.google.protobuf.MapField.newMapField(
                    Mtd2FreqDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              mtd2Freq__ = input.readMessage(
                  Mtd2FreqDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mtd2Freq_.getMutableMap().put(
                  mtd2Freq__.getKey(), mtd2Freq__.getValue());
              break;
            }
            case 24: {

              sum_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return presto.ProfileOuterClass.internal_static_presto_ProfileInt_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMtd2Freq();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return presto.ProfileOuterClass.internal_static_presto_ProfileInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              presto.ProfileOuterClass.ProfileInt.class, presto.ProfileOuterClass.ProfileInt.Builder.class);
    }

    public static final int MTD2FREQ_FIELD_NUMBER = 2;
    private static final class Mtd2FreqDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Long>newDefaultInstance(
                  presto.ProfileOuterClass.internal_static_presto_ProfileInt_Mtd2freqEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> mtd2Freq_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetMtd2Freq() {
      if (mtd2Freq_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            Mtd2FreqDefaultEntryHolder.defaultEntry);
      }
      return mtd2Freq_;
    }

    public int getMtd2FreqCount() {
      return internalGetMtd2Freq().getMap().size();
    }
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */

    public boolean containsMtd2Freq(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMtd2Freq().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMtd2FreqMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getMtd2Freq() {
      return getMtd2FreqMap();
    }
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Long> getMtd2FreqMap() {
      return internalGetMtd2Freq().getMap();
    }
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */

    public long getMtd2FreqOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetMtd2Freq().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
     */

    public long getMtd2FreqOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetMtd2Freq().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int SUM_FIELD_NUMBER = 3;
    private long sum_;
    /**
     * <code>int64 sum = 3;</code>
     * @return The sum.
     */
    public long getSum() {
      return sum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMtd2Freq(),
          Mtd2FreqDefaultEntryHolder.defaultEntry,
          2);
      if (sum_ != 0L) {
        output.writeInt64(3, sum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
           : internalGetMtd2Freq().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
        mtd2Freq__ = Mtd2FreqDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, mtd2Freq__);
      }
      if (sum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof presto.ProfileOuterClass.ProfileInt)) {
        return super.equals(obj);
      }
      presto.ProfileOuterClass.ProfileInt other = (presto.ProfileOuterClass.ProfileInt) obj;

      if (!internalGetMtd2Freq().equals(
          other.internalGetMtd2Freq())) return false;
      if (getSum()
          != other.getSum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetMtd2Freq().getMap().isEmpty()) {
        hash = (37 * hash) + MTD2FREQ_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMtd2Freq().hashCode();
      }
      hash = (37 * hash) + SUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSum());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static presto.ProfileOuterClass.ProfileInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static presto.ProfileOuterClass.ProfileInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static presto.ProfileOuterClass.ProfileInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(presto.ProfileOuterClass.ProfileInt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code presto.ProfileInt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:presto.ProfileInt)
        presto.ProfileOuterClass.ProfileIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return presto.ProfileOuterClass.internal_static_presto_ProfileInt_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMtd2Freq();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableMtd2Freq();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return presto.ProfileOuterClass.internal_static_presto_ProfileInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                presto.ProfileOuterClass.ProfileInt.class, presto.ProfileOuterClass.ProfileInt.Builder.class);
      }

      // Construct using presto.ProfileOuterClass.ProfileInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableMtd2Freq().clear();
        sum_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return presto.ProfileOuterClass.internal_static_presto_ProfileInt_descriptor;
      }

      @java.lang.Override
      public presto.ProfileOuterClass.ProfileInt getDefaultInstanceForType() {
        return presto.ProfileOuterClass.ProfileInt.getDefaultInstance();
      }

      @java.lang.Override
      public presto.ProfileOuterClass.ProfileInt build() {
        presto.ProfileOuterClass.ProfileInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public presto.ProfileOuterClass.ProfileInt buildPartial() {
        presto.ProfileOuterClass.ProfileInt result = new presto.ProfileOuterClass.ProfileInt(this);
        int from_bitField0_ = bitField0_;
        result.mtd2Freq_ = internalGetMtd2Freq();
        result.mtd2Freq_.makeImmutable();
        result.sum_ = sum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof presto.ProfileOuterClass.ProfileInt) {
          return mergeFrom((presto.ProfileOuterClass.ProfileInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(presto.ProfileOuterClass.ProfileInt other) {
        if (other == presto.ProfileOuterClass.ProfileInt.getDefaultInstance()) return this;
        internalGetMutableMtd2Freq().mergeFrom(
            other.internalGetMtd2Freq());
        if (other.getSum() != 0L) {
          setSum(other.getSum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        presto.ProfileOuterClass.ProfileInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (presto.ProfileOuterClass.ProfileInt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Long> mtd2Freq_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
      internalGetMtd2Freq() {
        if (mtd2Freq_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              Mtd2FreqDefaultEntryHolder.defaultEntry);
        }
        return mtd2Freq_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
      internalGetMutableMtd2Freq() {
        onChanged();;
        if (mtd2Freq_ == null) {
          mtd2Freq_ = com.google.protobuf.MapField.newMapField(
              Mtd2FreqDefaultEntryHolder.defaultEntry);
        }
        if (!mtd2Freq_.isMutable()) {
          mtd2Freq_ = mtd2Freq_.copy();
        }
        return mtd2Freq_;
      }

      public int getMtd2FreqCount() {
        return internalGetMtd2Freq().getMap().size();
      }
      /**
       * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
       */

      public boolean containsMtd2Freq(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMtd2Freq().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMtd2FreqMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Long> getMtd2Freq() {
        return getMtd2FreqMap();
      }
      /**
       * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Long> getMtd2FreqMap() {
        return internalGetMtd2Freq().getMap();
      }
      /**
       * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
       */

      public long getMtd2FreqOrDefault(
          java.lang.String key,
          long defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Long> map =
            internalGetMtd2Freq().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
       */

      public long getMtd2FreqOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Long> map =
            internalGetMtd2Freq().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMtd2Freq() {
        internalGetMutableMtd2Freq().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
       */

      public Builder removeMtd2Freq(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMtd2Freq().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Long>
      getMutableMtd2Freq() {
        return internalGetMutableMtd2Freq().getMutableMap();
      }
      /**
       * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
       */
      public Builder putMtd2Freq(
          java.lang.String key,
          long value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableMtd2Freq().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int64&gt; mtd2freq = 2;</code>
       */

      public Builder putAllMtd2Freq(
          java.util.Map<java.lang.String, java.lang.Long> values) {
        internalGetMutableMtd2Freq().getMutableMap()
            .putAll(values);
        return this;
      }

      private long sum_ ;
      /**
       * <code>int64 sum = 3;</code>
       * @return The sum.
       */
      public long getSum() {
        return sum_;
      }
      /**
       * <code>int64 sum = 3;</code>
       * @param value The sum to set.
       * @return This builder for chaining.
       */
      public Builder setSum(long value) {
        
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSum() {
        
        sum_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:presto.ProfileInt)
    }

    // @@protoc_insertion_point(class_scope:presto.ProfileInt)
    private static final presto.ProfileOuterClass.ProfileInt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new presto.ProfileOuterClass.ProfileInt();
    }

    public static presto.ProfileOuterClass.ProfileInt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProfileInt>
        PARSER = new com.google.protobuf.AbstractParser<ProfileInt>() {
      @java.lang.Override
      public ProfileInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProfileInt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProfileInt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProfileInt> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public presto.ProfileOuterClass.ProfileInt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presto_Profile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presto_Profile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presto_Profile_Mtd2freqEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presto_Profile_Mtd2freqEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presto_ProfileInt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presto_ProfileInt_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presto_ProfileInt_Mtd2freqEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presto_ProfileInt_Mtd2freqEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprofile.proto\022\006presto\"k\n\007Profile\022/\n\010mt" +
      "d2freq\030\001 \003(\0132\035.presto.Profile.Mtd2freqEn" +
      "try\032/\n\rMtd2freqEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\001:\0028\001\"~\n\nProfileInt\0222\n\010mtd2freq\030\002" +
      " \003(\0132 .presto.ProfileInt.Mtd2freqEntry\022\013" +
      "\n\003sum\030\003 \001(\003\032/\n\rMtd2freqEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\003:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_presto_Profile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_presto_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presto_Profile_descriptor,
        new java.lang.String[] { "Mtd2Freq", });
    internal_static_presto_Profile_Mtd2freqEntry_descriptor =
      internal_static_presto_Profile_descriptor.getNestedTypes().get(0);
    internal_static_presto_Profile_Mtd2freqEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presto_Profile_Mtd2freqEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_presto_ProfileInt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_presto_ProfileInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presto_ProfileInt_descriptor,
        new java.lang.String[] { "Mtd2Freq", "Sum", });
    internal_static_presto_ProfileInt_Mtd2freqEntry_descriptor =
      internal_static_presto_ProfileInt_descriptor.getNestedTypes().get(0);
    internal_static_presto_ProfileInt_Mtd2freqEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presto_ProfileInt_Mtd2freqEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
